doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        dql:
            datetime_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                DAY: DoctrineExtensions\Query\Mysql\Day
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                date_format: DoctrineExtensions\Query\Postgresql\DateFormat
                at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                date_part: DoctrineExtensions\Query\Postgresql\DatePart
                extract: DoctrineExtensions\Query\Postgresql\ExtractFunction
            string_functions:
                str_to_date: DoctrineExtensions\Query\Postgresql\StrToDate
                count_filter: DoctrineExtensions\Query\Postgresql\CountFilterFunction
                string_agg: DoctrineExtensions\Query\Postgresql\StringAgg
                greatest: DoctrineExtensions\Query\Postgresql\Greatest
                least: DoctrineExtensions\Query\Postgresql\Least
                regexp_replace: DoctrineExtensions\Query\Postgresql\RegexpReplace

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
